### ISSUE TITLE
Error in header decoding

### ISSUE THREAD

**Issue by sebdelp** [kwikteam/npy-matlab#11]
I've got a file with the header provided below.
The readNPYheader.m file is not able to decode it. I think the problem comes from the regexpr at line 49, which returns empty values.
" r = regexp(arrayFormat, '''descr''\s*:\s*''(.*?)''', 'tokens');"

For debuging purpose, the arrayFormat contains:
'{'descr': [('measure_coursestddev_43200', '<f8'), ('measure_speedavg_86400', '<f8'), ('measure_coursestddev_1800_log', '<f8'), ('measure_coursestddev_10800_log', '<f8'), ('measure_courseavg_43200', '<f8'), ('measure_cos_course', '<f8'), ('measure_daylightavg_1800', '<f8'), ('measure_coursestddev_21600', '<f8'), ('measure_speedstddev_1800', '<f8'), ('measure_distance_from_port', '<f8'), ('measure_count_1800', '<f8'), ('course', '<f8'), ('measure_sin_course', '<f8'), ('measure_speedstddev_10800', '<f8'), ('measure_speedavg_21600', '<f8'), ('speed', '<f8'), ('is_fishing', '<f8'), ('measure_pos_86400', '<f8'), ('measure_daylightavg_43200', '<f8'), ('measure_latavg_86400', '<f8'), ('measure_latavg_10800', '<f8'), ('distance_from_port', '<f8'), ('measure_latavg_1800', '<f8'), ('measure_pos_1800', '<f8'), ('measure_lonavg_3600', '<f8'), ('measure_count_3600', '<f8'), ('lon', '<f8'), ('measure_speedavg_10800', '<f8'), ('measure_latavg_3600', '<f8'), ('measure_coursestddev_43200_log', '<f8'), ('measure_latavg_21600', '<f8'), ('measure_daylightavg_10800', '<f8'), ('measure_count_86400', '<f8'), ('measure_count_21600', '<f8'), ('measure_speedstddev_86400_log', '<f8'), ('measure_lonavg_1800', '<f8'), ('measure_courseavg_10800', '<f8'), ('measure_speedstddev_3600', '<f8'), ('measure_lonavg_10800', '<f8'), ('measure_course', '<f8'), ('measure_pos_43200', '<f8'), ('distance_from_shore', '<f8'), ('measure_courseavg_1800', '<f8'), ('measure_pos_3600', '<f8'), ('measure_speedstddev_86400', '<f8'), ('measure_coursestddev_21600_log', '<f8'), ('measure_lonavg_21600', '<f8'), ('timestamp', '<f8'), ('measure_speedstddev_21600_log', '<f8'), ('measure_coursestddev_86400_log', '<f8'), ('measure_speedavg_43200', '<f8'), ('measure_coursestddev_86400', '<f8'), ('measure_speedavg_3600', '<f8'), ('measure_courseavg_3600', '<f8'), ('measure_speedstddev_21600', '<f8'), ('measure_daylightavg_86400', '<f8'), ('lat', '<f8'), ('measure_count_43200', '<f8'), ('measure_daylightavg_3600', '<f8'), ('mmsi', '<f8'), ('measure_pos_10800', '<f8'), ('measure_count_10800', '<f8'), ('measure_speedstddev_43200_log', '<f8'), ('measure_coursestddev_3600', '<f8'), ('measure_speedstddev_43200', '<f8'), ('measure_courseavg_86400', '<f8'), ('measure_lonavg_86400', '<f8'), ('measure_speedstddev_3600_log', '<f8'), ('measure_latavg_43200', '<f8'), ('measure_speedstddev_10800_log', '<f8'), ('measure_daylightavg_21600', '<f8'), ('measure_daylight', '<f8'), ('measure_coursestddev_1800', '<f8'), ('measure_pos_21600', '<f8'), ('measure_coursestddev_3600_log', '<f8'), ('measure_speedavg_1800', '<f8'), ('measure_lonavg_43200', '<f8'), ('measure_speedstddev_1800_log', '<f8'), ('measure_courseavg_21600', '<f8'), ('measure_coursestddev_10800', '<f8'), ('measure_speed', '<f8')], 'fortran_order': False, 'shape': (133950,), }               
     '

I would greatly appreciate if you could give me a hint on how to solve this issue, I'm not so familiar with regexpr..

Best regards
Seb

The header of my file

“NUMPY {'descr': [('measure_coursestddev_43200', '<f8'), ('measure_speedavg_86400', '<f8'), ('measure_coursestddev_1800_log', '<f8'), ('measure_coursestddev_10800_log', '<f8'), ('measure_courseavg_43200', '<f8'), ('measure_cos_course', '<f8'), ('measure_daylightavg_1800', '<f8'), ('measure_coursestddev_21600', '<f8'), ('measure_speedstddev_1800', '<f8'), ('measure_distance_from_port', '<f8'), ('measure_count_1800', '<f8'), ('course', '<f8'), ('measure_sin_course', '<f8'), ('measure_speedstddev_10800', '<f8'), ('measure_speedavg_21600', '<f8'), ('speed', '<f8'), ('is_fishing', '<f8'), ('measure_pos_86400', '<f8'), ('measure_daylightavg_43200', '<f8'), ('measure_latavg_86400', '<f8'), ('measure_latavg_10800', '<f8'), ('distance_from_port', '<f8'), ('measure_latavg_1800', '<f8'), ('measure_pos_1800', '<f8'), ('measure_lonavg_3600', '<f8'), ('measure_count_3600', '<f8'), ('lon', '<f8'), ('measure_speedavg_10800', '<f8'), ('measure_latavg_3600', '<f8'), ('measure_coursestddev_43200_log', '<f8'), ('measure_latavg_21600', '<f8'), ('measure_daylightavg_10800', '<f8'), ('measure_count_86400', '<f8'), ('measure_count_21600', '<f8'), ('measure_speedstddev_86400_log', '<f8'), ('measure_lonavg_1800', '<f8'), ('measure_courseavg_10800', '<f8'), ('measure_speedstddev_3600', '<f8'), ('measure_lonavg_10800', '<f8'), ('measure_course', '<f8'), ('measure_pos_43200', '<f8'), ('distance_from_shore', '<f8'), ('measure_courseavg_1800', '<f8'), ('measure_pos_3600', '<f8'), ('measure_speedstddev_86400', '<f8'), ('measure_coursestddev_21600_log', '<f8'), ('measure_lonavg_21600', '<f8'), ('timestamp', '<f8'), ('measure_speedstddev_21600_log', '<f8'), ('measure_coursestddev_86400_log', '<f8'), ('measure_speedavg_43200', '<f8'), ('measure_coursestddev_86400', '<f8'), ('measure_speedavg_3600', '<f8'), ('measure_courseavg_3600', '<f8'), ('measure_speedstddev_21600', '<f8'), ('measure_daylightavg_86400', '<f8'), ('lat', '<f8'), ('measure_count_43200', '<f8'), ('measure_daylightavg_3600', '<f8'), ('mmsi', '<f8'), ('measure_pos_10800', '<f8'), ('measure_count_10800', '<f8'), ('measure_speedstddev_43200_log', '<f8'), ('measure_coursestddev_3600', '<f8'), ('measure_speedstddev_43200', '<f8'), ('measure_courseavg_86400', '<f8'), ('measure_lonavg_86400', '<f8'), ('measure_speedstddev_3600_log', '<f8'), ('measure_latavg_43200', '<f8'), ('measure_speedstddev_10800_log', '<f8'), ('measure_daylightavg_21600', '<f8'), ('measure_daylight', '<f8'), ('measure_coursestddev_1800', '<f8'), ('measure_pos_21600', '<f8'), ('measure_coursestddev_3600_log', '<f8'), ('measure_speedavg_1800', '<f8'), ('measure_lonavg_43200', '<f8'), ('measure_speedstddev_1800_log', '<f8'), ('measure_courseavg_21600', '<f8'), ('measure_coursestddev_10800', '<f8'), ('measure_speed', '<f8')], 'fortran_order': False, 'shape': (133950,), }

**Comment by nsteinme** [comment]
What type of variable is in the file? Only data matrices are supported by this library, not any more complex variable types. Closing the issue for now - feel free to re-open if I mis-understood.
