### ISSUE TITLE
readNPY for 3D arrays

### ISSUE THREAD

**Issue by LGurtner** [kwikteam/npy-matlab#3]
Dear all, 

I just tried to use the readNPY function to import a 3D (512 x 512 x 400) .npy file in Matlab and received the following error: 'This file does not appear to be NUMPY format based on the header.' The error refers to the strcmp of magicString (in the function readNPYheader, which is 'NUMPY' in my case, and '?NUMPY'. 

Is there a possibility to import 3D arrays with readNPY? 

Thank you for your help!

**Comment by nsteinme** [comment]
How did you create this file? If it was created with numpy or with this
repository's writeNPY function then the header should match. It does work
in general for 3D arrays, I use this all the time.

**Comment by LGurtner** [comment]
The arrays are grey values in a 512x512 white noise Image. I present the images iteratively in PsychoPy. After presentation, I attach the current "texture" (the 2D np-array) to the others using np.dstack. Then I use np.save to generate the 3D npy-file. The function np.savetxt dosen't work...

**Comment by nsteinme** [comment]
I wonder whether it might be an OS issue - are you using Windows? Or, do
you know whether you have the most current version of numpy? Basically, the
link below is the specification, and that explains (under "format
specification") what my matlab code is supposed to be looking for at the
beginning of your file. If it isn't there, then you get this error. Can you
try to check whether it is there in your file?

https://docs.scipy.org/doc/numpy-dev/neps/npy-format.html

**Comment by rossant** [comment]
can you upload the file somewhere so that we can test too?

**Comment by LGurtner** [comment]
I am using OS X 10.11.6, np is version 1.8.0rc1, during upgrading there was an execution error: 
'The directory '/Users/XXX/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.'

I will send you the file via email since GitHub apparently dosen't support .npy attachments...

**Comment by LGurtner** [comment]
When I print out the magicString from your functions, the result is 'NUMPY', but if I do the same thing from the command window, the magicString is empty. 
The mail with my file just came back, it's not possible to send it to you. I am new to GitHub, how can I make the file available to you?

**Comment by rossant** [comment]
if you zip the file you should be able to attach it here https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by LGurtner** [comment]
Here you go, thanks!

[noise.npy.zip](https://github.com/kwikteam/npy-matlab/files/583671/noise.npy.zip)

**Comment by nsteinme** [comment]
Hi,

Sorry for the delay, was out of town. I was not able to reproduce any
problems with the file you sent, you can see what I got below. This test
was on OSX 10.10.3 with matlab 2015a, but I doubt either of those versions
are the problem. As a test/workaround you could disable to check about the
magic string in readNPYheader and see whether it loads correctly then?

Nick

> > q = readNPY('noise.npy');
> > whos q
> >   Name        Size                  Bytes  Class     Attributes

  q         512x512x5            10485760  double

> > q(1:5,1:5,1)

ans =

   -0.0152   -0.9152   -0.5480   -0.3436   -0.9497
    0.8835    0.9787    0.5860    0.2463    0.5885
    0.7208   -0.2297   -0.4088    0.9710    0.9700
   -0.5309    0.7726   -0.1024   -0.0848    0.3733
   -0.9738   -0.4441   -0.2376    0.9167    0.7288

**Comment by nschaeff** [comment]
Hello,
I have the same problem here on linux.
I solved it by replacing line 31 in readNPYheader with:
`         if ~strcmp(magicString, strcat(char(0x93),'NUMPY'))`
This should always work, whatever the charset/OS is.

By the way, I found another typo, line 40 of readNPYheader should be replaced with:
`    headerLength = fread(fid, [1 1], 'uint16=>uint16');`

Thanks for the code !

**Comment by nsteinme** [comment]
Ah fantastic, thanks for this. 

@LGurtner let us know if this solves your issue, and I'll implement (or, @nschaeff, feel free to make a PR...).

**Comment by nsteinme** [comment]
I have updated with both of these fixes (not sure why "unit16" wasn't throwing an error...? good catch). Please re-open if the issue isn't solved.
