### ISSUE TITLE
Problem in readNPYheader.py

### ISSUE THREAD

**Issue by caiya55** [kwikteam/npy-matlab#5]
download and run the example and get an error like this:

Error using readNPYheader (line 32)
Error: This file does not appear to be NUMPY format based on the header.

So I debug the code and realize that the six char that I get from the fopean function is [25560   85   77  80       89], Apparently, my system recognize the the first two uint8 character into one character (Chinese system), and I realize my 31th code is different from Github:

---------if ~strcmp(magicString, '揘UMPY')
so I change the code ,make it more robust. In readNPYheader, from line29 to line 33:

    magicString = fread(fid, [1 6], 'uchar=>uchar');
    
    if  ~all(magicString == [147,78,85,77,80,89])
        error('readNPY:NotNUMPYFile', 'Error: This file does not appear to be NUMPY format based on the header.');
    end

And it works well。 May it helpful for to any un-English system

**Comment by yuleichin** [comment]
Thanks, it works for CN system.

**Comment by qysnn** [comment]
Yes. That solves my problem.

**Comment by nsteinme** [comment]
Thanks all - I've made the change.
